xunfei_asr:
  app_id: "016b92a6"
  api_key: "8ac63485f16c76f845142189872f5cea"
  api_secret: "MjUzZjZmZjFkOTllMDYwYjljYzhlYWE2"
  hotwords: "小猪猪,芝麻开门"

xunfei:
  app_id: "016b92a6"
  api_key: "8ac63485f16c76f845142189872f5cea"
  api_secret: "MjUzZjZmZjFkOTllMDYwYjljYzhlYWE2"
  vcn: "x4_yezi"
  speed: 50
  volume: 50
  pitch: 50

deepseek:
  api_key: "sk-f2d5403d07e1499a8e344a09588f4eb7"
  base_url: "https://api.deepseek.com"
  model: "deepseek-chat"
  temperature: 0.7
  max_tokens: 2048
  system_prompt: "这是背景设定，你不需要在后面的对话中提及，但是要一直记住：你是我给我女儿设计的智能语音音箱，她叫嘟嘟，你是一个知性、温柔的大姐姐，她会亲密地叫你小猪猪，由于语音音箱的识别问题，发送给你的文字会有倒序或者重复的问题，请你自动理解，并且当作正常的语言来处理。你回答中的所有文字会直接被读出来，所以不要以括号的形式表现情绪等内容。"

endwords:
  - "再见"
  - "拜拜"
  - "下次再说"

welcome_audio_path: "audio_out/welcome.mp3"
welcome_text: "你好。"
audio_out_dir: "audio_out"
tts_cache_dir: "audio_out/tts_cache"

# 标准化异常播报文本
error_prompts:
  error_recording: "录音设备不可用，请检查麦克风。"
  error_asr: "语音识别服务不可用，请检查网络或稍后重试。"
  error_network: "网络连接异常，请检查网络。"
  error_tts: "语音合成服务不可用。"
  error_system: "系统发生未知错误，请稍后重试。"
  error_no_input: "未检测到有效语音，请再试一次。"

wakeword:
  keyword_paths: ["wakeword/xiaozhu.ppn"]
  access_key: "TTnalPNKGniQ17wPRKfQR7u29VGYKVHk2NheRgMh7K7b5JIVnJE3UQ=="
  sensitivities: [0.7]
  model_path: "wakeword/porcupine_params_zh.pv"
  audio_device_index: 1

tts_cache_policy:
  max_files: 200        # 最大保留音频文件数
  max_bytes: 15000000000 # 最大总容量，单位为字节（如15GB）

