wakeword:
  keywords: ["xiaozhu_xiaozhu"]
  access_key: "YOUR_PICOVOICE_ACCESS_KEY"
  keyword_paths:
    - "wakeword/xiaozhu_xiaozhu.ppn"  # 你的自定义唤醒词文件

endwords:
  - "再见"
  - "拜拜"
  - "下次再说"
  - "回头聊"
  - "关闭"

deepseek:
  api_key: "YOUR_DEEPSEEK_API_KEY"

xunfei:
  app_id: "YOUR_XUNFEI_APP_ID"
  api_key: "YOUR_XUNFEI_API_KEY"
  api_secret: "YOUR_XUNFEI_API_SECRET"
