wakeword:
  keywords: ["xiaozhu_xiaozhu"]
  access_key: "YOUR_PICOVOICE_ACCESS_KEY"
  keyword_paths:
    - "wakeword/xiaozhu_xiaozhu.ppn"  # 你的自定义唤醒词文件

endwords:
  - "再见"
  - "拜拜"
  - "下次再说"
  - "回头聊"
  - "关闭"

deepseek:
  api_key: "YOUR_DEEPSEEK_API_KEY"

xunfei_asr:
  app_id: "你的APPID"
  api_key: "你的APIKey"
  api_secret: "你的APISecret"
  hotwords: "小猪小猪,芝麻开门,嘟嘟,科大讯飞"

